

services:
  router:
    build: ./router
    ports:
      - "3000:3000"
    depends_on:
      - business

  business:
    build: ./business
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - PGDATABASE=tododb
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
